# Generated by Django 5.1.7 on 2025-03-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introcard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='slug',
            new_name='details',
        ),
        migrations.AddField(
            model_name='card',
            name='featured_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
