# Generated by Django 5.1.7 on 2025-03-13 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introcard', '0002_rename_slug_card_details_card_featured_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='details',
        ),
    ]
