# Generated by Django 5.1.7 on 2025-03-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introcard', '0003_remove_card_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
