# Generated by Django 5.1.7 on 2025-03-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introcard', '0005_alter_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
