# Generated by Django 5.1.7 on 2025-03-15 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introcard', '0006_card_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.CharField(blank=True, choices=[('Metal_White', 'Metal White'), ('Metal_Black', 'Metal Black'), ('PVC_White', 'PVC_White'), ('PVC_Black', 'PVC Black')], max_length=255, null=True),
        ),
    ]
