# Generated by Django 5.1.7 on 2025-03-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introcard', '0007_alter_card_author_alter_card_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('Ubique_Logo', 'Ubique Logo'), ('Custom_Logo', 'Custom Logo')], max_length=255, null=True),
        ),
    ]
