# Generated by Django 5.1.7 on 2025-03-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introcard', '0008_card_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
