# Generated by Django 5.1.7 on 2025-03-17 06:41

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introcard', '0009_customuser_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
