# Generated by Django 5.1.7 on 2025-03-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introcard', '0010_customuser_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.URLField(blank=True, null=True),
        ),
    ]
