# Generated by Django 5.1.7 on 2025-03-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introcard', '0011_customuser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
