# Generated by Django 5.1.7 on 2025-03-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introcard', '0012_customuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.CharField(blank=True, choices=[('Metal White', 'Metal White'), ('Metal Black', 'Metal Black'), ('PVC White', 'PVC White'), ('PVC Black', 'PVC Black')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('Ubique Logo', 'Ubique Logo'), ('Custom Logo', 'Custom Logo')], max_length=255, null=True),
        ),
    ]
